muhlba91/fh-burgenland-bswe-assignment-infrastructure

.github/workflows/codeql.yml
.github/workflows/dependency_review.yml
.github/workflows/pipeline.yml
.github/workflows/pr.yml
.github/workflows/scorecard.yml
.pre-commit-config.yaml
README.md

adds repository security scanning

chore: introduce repository and project security scanning

---

assets/data_ws2024.yaml

The accounts repository for group h need required workflow checks to allow merging. For further details please read the following issue: #50 
- fixes #50 
- [x ] New feature (non-breaking change which adds functionality)

Group H - chore: add required workflow checks for pull requests

---

assets/data_ws2024.yaml

This PR will add java unit tests to the required checks for a pull request.
https://github.com/fhburgenland-bswe/swm2-ws2024-group-h-accounts/issues/29

Group H - chore: add required check for java unit tests for pull request

---

assets/data_ws2024.yaml

This PR adds the workflows for Unit Tests, commit Unit Tests as requirement for future pull requests in our Transaction project.
[*fhburgenland-bswe/swm2-ws2024-group-h-transactions#17*](https://github.com/fhburgenland-bswe/swm2-ws2024-group-h-transactions/issues/17)

Group H - chore: add Unit Tests as requirement for Transaction PRs

---

assets/data_ws2024.yaml

Adds required checks to be added to [group-a's transaction repo](https://github.com/fhburgenland-bswe/swm2-ws2024-group-a-transactions). See Below Issue for details
- CheckstyleMain: for checking the defined style guilde
- Test: Unit tests need to run green
- bootjar: Project is buildable
- Spectral Linter: checks .yaml files
- YAMLLint: also checks .yaml files
- fixes [Set Up GitHub Actions Pipeline with Mandatory Checks](https://github.com/fhburgenland-bswe/swm2-ws2024-group-a-transactions/issues/6)
- relates to: [feat: set up git hub actions pipeline and relevant checks](https://github.com/fhburgenland-bswe/swm2-ws2024-group-a-transactions/issues/6)

feat: action pipeline for transaction service infrastructure group-a

---

assets/data_ws2024.yaml

test: Unit tests 
conform: 
spectral: 
yamllint: checks the .yaml files
build: builds the project
- fixes #15
- [ x] CI/CD pipline change

feat: action pipeline for account service

---

assets/data_ws2024.yaml

This PR adds required checks to PRs for the Groub B Account service. The checks are:
- Validate commit
- Validate Java code (Checkstyle, PMD and SBOM Scanning)
- Lint Dockerfile
https://github.com/fhburgenland-bswe/swm2-ws2024-group-b-accounts/issues/3

feat: add required checks for group-b-accounts

---

assets/data_ws2024.yaml

This PR adds the workflows for Java Checkstyles, Commit Policies and YAML Lint as a requirenment for future pull requests in the broker repository of group hk.
https://github.com/fhburgenland-bswe/swm2-ws2024-group-hk-broker/issues/12

Group HK - feat: add policies and linting as required checks

---

assets/data_ws2024.yaml

This PR will add Github Action Checks for the Broker Repo Group A and J 
Its part of the Setup procedere. 
Checks that should be implemented: 
- CheckstyleMain - To conform our Code Styleguide.
- Test - To validate all written Tests during changes. 
- bootjar - To validate the project is still bootable with new changes.
- Spectral Linter & YAMLLint - To validate the API documentation

docs: group-aj broker checks

---

assets/data_ws2024.yaml

Add requiered checks for transaction service of group B.
https://github.com/fhburgenland-bswe/swm2-ws2024-group-b-transactions/issues/3

feat: add required checks for group b transactions

---

assets/data_ws2024.yaml

Added require checks for broker-service - Group BC
https://github.com/fhburgenland-bswe/swm2-ws2024-group-bc-broker/issues/2

feat: add requiredChecks for broker-service - Group BC

---

assets/data_ws2024.yaml

test: Unit tests 
conform: 
spectral: 
yamllint: checks the .yaml files
build: builds the project
- fixes #11
- [ x] CI/CD pipline change

feat: action pipeline for transaction service for group-k

---

assets/data_ws2024.yaml

*Please include a summary of the changes and the related issue.*
*Please reference the issue that this PR is related to. The issue can be located either in this repository or an assignment-specific repository.*
- fixes [#18](https://github.com/fhburgenland-bswe/swm2-ws2024-group-j-accounts/issues/18)
*Provide any additional information that might be useful to the reviewer in evaluating this pull request.*

feat: add requiredChecks for account-service (group J); fixes #18

---

assets/data_ws2024.yaml

*Please include a summary of the changes and the related issue.*
*Please reference the issue that this PR is related to. The issue can be located either in this repository or an assignment-specific repository.*
- fixes [#9](https://github.com/fhburgenland-bswe/swm2-ws2024-group-j-transactions/issues/9)
*Provide any additional information that might be useful to the reviewer in evaluating this pull request.*

add requiredChecks for transaction-service (group J)

---

assets/data_ws2024.yaml

Added branch protection rules for the `main` branch:
- Enforce CI checks (`build` and `tests`) before merging.
- Require at least 2 approving reviews for pull requests.
- Apply rules to administrators.
[swm2-ws2024-group-l-accounts#19](https://github.com/fhburgenland-bswe/swm2-ws2024-group-l-accounts/issues/19)

feat(branch-protection): add rules for swm2-ws2024-group-l-accounts repository

---

assets/data_ws2024.yaml

This PR will add the following checks to the required checks for the frontend reposiotry of group hk:
- `YAMLLint` for validating the format of yaml files.
- `AngularLint` for validating the format of angular/typescript files.
- `Conform` for enforcing git commit conventions.
https://github.com/fhburgenland-bswe/swm2-ws2024-group-hk-frontend/issues/2

Group HK - chore: add linting to required frontend checks

---

assets/data_ws2024.yaml

Adds requiredChecks for group-aj frontend:
- InstallAndBuild
- Lint
- Test
*Relates to [PR 10 in swm2-ws2024-group-aj-frontend](https://github.com/fhburgenland-bswe/swm2-ws2024-group-aj-frontend/pull/10)*

feat: group aj frontend checks

---

assets/data_ws2024.yaml

Add required checks for transaction service of group c.
https://github.com/fhburgenland-bswe/swm2-ws2024-group-c-transactions/issues/24

feat: add required checks for group c transactions

---

assets/data_ws2024.yaml

Add required checks for the frontend of group bc.
https://github.com/fhburgenland-bswe/swm2-ws2024-group-bc-frontend/issues/2

feat: add required checks for group-bc-frontend

---

assets/data_ws2024.yaml

This PR will add the Angular Testing Workflow to the required checks for the frontend repository of group HK.
This will ensure that all tests (unit tests and end-to-end tests) have to pass in order to contribute to the main/production branch.
https://github.com/fhburgenland-bswe/swm2-ws2024-group-hk-frontend/issues/20

Group HK - chore: add frontend tests to required checks

---

assets/data_ws2024.yaml

This PR adds the required Checks for a PR in group g Accounts.
- Closes https://github.com/fhburgenland-bswe/swm2-ws2024-group-g-accounts/issues/49

feat: add required checks for accounts
